# HOMEKIT #
  - id: homekit
    alias: 'Start HomeKit'  
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:02  # Waits 2 minutes
      - service: homekit.start

# LIGHTS #
  - id: kantoormotion
    alias: 'Turn on kantoor light when there is movement'
    trigger:
      - platform: state
        entity_id: binary_sensor.sensor
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.aeotec_zw100_multisensor_6_luminance
          below: 10
        - condition: state
          entity_id: light.level_2
          state: 'off'
        - condition: state
          entity_id: light.level
          state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.level_2
          brightness: 200
      - service: light.turn_on
        data_template:
          entity_id: light.level
          brightness: 200

  - id: kantoormotionoff
    alias: 'Turn off light after 30 minutes of no motion'
    trigger:
      platform: state
      entity_id: binary_sensor.sensor
      to: 'off'
      for:
        minutes: 30
    action:
      - service: homeassistant.turn_off
        entity_id: light.level_2
      - service: homeassistant.turn_off
        entity_id: light.level

# DIMMERS #
  - id: kantoor_right_dimmer
    alias: 'Kantoor_right dimmer'
    trigger:
      platform: state
      entity_id: input_number.kantoor_right_dimmer
    action:
      service: light.turn_on
      data_template:
        entity_id: light.level_2
        brightness_pct: '{{trigger.to_state.state | int}}'
  - id: kantoor_right_dimmer_sync
    alias: 'Kantoor_right dimmer reactie aan'
    trigger:
      platform: state
      entity_id: light.level_2
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.kantoor_right_dimmer
        value: '{{states.light.level_2.attributes.brightness | int / 2.55}}'

  - alias: 'Kantoor_left dimmer'
    trigger:
      platform: state
      entity_id: input_number.kantoor_left_dimmer
    action:
      service: light.turn_on
      data_template:
        entity_id: light.level
        brightness: '{{states.input_number.kantoor_left_dimmer.state | int}}'
  - alias: 'Kantoor_left dimmer reactie'
    trigger:
      platform: state
      entity_id: light.level
      to: 'off'
    action:
      service: input_number.set_value
      data:
        entity_id: input_number.kantoor_left_dimmer
        value: '0'
  - alias: 'Kantoor_left dimmer reactie aan'
    trigger:
      platform: state
      entity_id: light.level
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.kantoor_left_dimmer
        value: '{{states.light.level.attributes.brightness}}'

  - alias: 'hue_white_hal_boven dimmer'
    trigger:
      platform: state
      entity_id: input_number.hue_white_hal_boven
    action:
      service: light.turn_on
      data_template:
        entity_id: light.hue_white_hal_boven
        brightness: '{{states.input_number.hue_white_hal_boven.state | int}}'
  - alias: 'hue_white_hal_boven dimmer reactie'
    trigger:
      platform: state
      entity_id: light.hue_white_hal_boven
      to: 'off'
    action:
      service: input_number.set_value
      data:
        entity_id: input_number.hue_white_hal_boven
        value: '0'
  - alias: 'hue_white_hal_boven dimmer reactie aan'
    trigger:
      platform: state
      entity_id: light.hue_white_hal_boven
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.hue_white_hal_boven
        value: '{{states.light.hue_white_hal_boven.attributes.brightness}}'

  - alias: 'hue_white_hal_beneden dimmer'
    trigger:
      platform: state
      entity_id: input_number.hue_white_hal_beneden
    action:
      service: light.turn_on
      data_template:
        entity_id: light.hue_white_hal_beneden
        brightness: '{{states.input_number.hue_white_hal_beneden.state | int}}'
  - alias: 'hue_white_hal_beneden reactie'
    trigger:
      platform: state
      entity_id: light.hue_white_hal_beneden
      to: 'off'
    action:
      service: input_number.set_value
      data:
        entity_id: input_number.hue_white_hal_beneden
        value: '0'
  - alias: 'hue_white_hal_beneden reactie aan'
    trigger:
      platform: state
      entity_id: light.hue_white_hal_beneden
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.hue_white_hal_beneden
        value: '{{states.light.hue_white_hal_beneden.attributes.brightness}}'

  - alias: 'hue_white_bijkamer dimmer'
    trigger:
      platform: state
      entity_id: input_number.hue_white_bijkamer
    action:
      service: light.turn_on
      data_template:
        entity_id: light.hue_white_bijkamer
        brightness: '{{states.input_number.hue_white_bijkamer.state | int}}'
  - alias: 'hue_white_bijkamer reactie'
    trigger:
      platform: state
      entity_id: light.hue_white_bijkamer
      to: 'off'
    action:
      service: input_number.set_value
      data:
        entity_id: input_number.hue_white_bijkamer
        value: '0'
  - alias: 'hue_white_bijkamer dimmer reactie aan'
    trigger:
      platform: state
      entity_id: light.hue_white_bijkamer
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.hue_white_bijkamer
        value: '{{states.light.hue_white_bijkamer.attributes.brightness}}'

# Alarm
  - alias: 'Alarm Away'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_halboven
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_bijkamer
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_away
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
  - alias: Alarm Home
    hide_entity: True
    trigger:
      - platform: state
        entity_id: binary_sensor.sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_bijkamer
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_home
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
  - alias: 'Send notification when alarm triggered'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'triggered'
    action:
      - service: notify.notify
        data:
          message: "ALARM! Beweging gedetecteerd in de Spoorstraat"
      - service: command_line.start_siren
  - alias: 'Delete code after disarm'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'disarmed'
    action:
      - service: input_number.set_value
        entity_id: input_number.codepad
        data:
          value: '0'
      - service: shell_command.stop_siren
  - alias: 'Turn off everything when leaving'
    hide_entity: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
    action:
      - service: light.turn_off
        entity_id: group.all_lights
