# HOMEKIT #
  - alias: 'Start HomeKit'  
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:02  # Waits 2 minutes
      - service: homekit.start

# LIGHTS #
  - alias: 'Turn on kantoor light when there is movement'
    trigger:
      - platform: state
        entity_id: binary_sensor.sensor
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.aeotec_zw100_multisensor_6_luminance
          below: 15
        - condition: state
          entity_id: light.level_2
          state: 'off'
        - condition: state
          entity_id: light.level
          state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.level_2
          brightness: 200
      - service: light.turn_on
        data_template:
          entity_id: light.level
          brightness: 200

  - alias: 'Turn on hal beneden light when there is movement'
    trigger:
      - platform: state
        entity_id: binary_sensor.arlo_motion
        to: 'on'
    condition:
        - condition: state
          entity_id: light.hue_white_hal_beneden
          state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.hue_white_hal_beneden
          brightness: 200
        
# DIMMERS #
  - alias: 'Kantoor_right_2 dimmer'
    trigger:
      platform: state
      entity_id: input_number.kantoor_right_dimmer
    condition:
      condition: numeric_state
      entity_id: input_number.kantoor_right_dimmer
      above: 0
    action:
      service: light.turn_on
      data_template:
        entity_id: light.level_2
        brightness: '{{states.input_number.kantoor_right_dimmer.state | int}}'
  - alias: 'Kantoor_right_2 dimmer reactie'
    trigger:
      platform: state
      entity_id: light.level_2
      to: 'off'
    action:
      service: input_number.set_value
      data:
        entity_id: input_number.kantoor_right_dimmer
        value: 0
  - alias: 'Kantoor_left dimmer reactie aan'
    trigger:
      platform: state
      entity_id: light.level_2
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.kantoor_right_dimmer
        value: '{{states.light.level_2.attributes.brightness}}'

  - alias: 'Kantoor_left dimmer'
    trigger:
      platform: state
      entity_id: input_number.kantoor_left_dimmer
    condition:
      condition: numeric_state
      entity_id: input_number.kantoor_left_dimmer
      above: 0
    action:
      service: light.turn_on
      data_template:
        entity_id: light.level
        brightness: '{{states.input_number.kantoor_left_dimmer.state | int}}'
  - alias: 'Kantoor_left dimmer reactie'
    trigger:
      platform: state
      entity_id: light.level
      to: 'off'
    action:
      service: input_number.set_value
      data:
        entity_id: input_number.kantoor_left_dimmer
        value: 0
  - alias: 'Kantoor_left dimmer reactie aan'
    trigger:
      platform: state
      entity_id: light.level
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.kantoor_left_dimmer
        value: '{{states.light.level.attributes.brightness}}'

  - alias: 'hue_white_hal_boven dimmer'
    trigger:
      platform: state
      entity_id: input_number.hue_white_hal_boven_dimmer
    condition:
      condition: numeric_state
      entity_id: input_number.hue_white_hal_boven_dimmer
      above: 0
    action:
      service: light.turn_on
      data_template:
        entity_id: light.hue_white_hal_boven
        brightness: '{{states.input_number.hue_white_hal_boven_dimmer.state | int}}'
  - alias: 'hue_white_hal_boven dimmer reactie'
    trigger:
      platform: state
      entity_id: light.hue_white_hal_boven
      to: 'off'
    action:
      service: input_number.set_value
      data:
        entity_id: input_number.hue_white_hal_boven_dimmer
        value: '0'
  - alias: 'hue_white_hal_boven dimmer reactie aan'
    trigger:
      platform: state
      entity_id: light.hue_white_hal_boven
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.hue_white_hal_boven_dimmer
        value: '{{states.light.hue_white_hal_boven.attributes.brightness}}'

  - alias: 'hue_white_hal_beneden dimmer'
    trigger:
      platform: state
      entity_id: input_number.hue_white_hal_beneden_dimmer
    condition:
      condition: numeric_state
      entity_id: input_number.hue_white_hal_beneden_dimmer
      above: 0
    action:
      service: light.turn_on
      data_template:
        entity_id: light.hue_white_hal_beneden
        brightness: '{{states.input_number.hue_white_hal_beneden_dimmer.state | int}}'
  - alias: 'hue_white_hal_beneden reactie'
    trigger:
      platform: state
      entity_id: light.hue_white_hal_beneden
      to: 'off'
    action:
      service: input_number.set_value
      data:
        entity_id: input_number.hue_white_hal_beneden_dimmer
        value: '0'
  - alias: 'hue_white_hal_beneden reactie aan'
    trigger:
      platform: state
      entity_id: light.hue_white_hal_beneden
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.hue_white_hal_beneden_dimmer
        value: '{{states.light.hue_white_hal_beneden.attributes.brightness}}'

  - alias: 'hue_white_bijkamer dimmer'
    trigger:
      platform: state
      entity_id: input_number.hue_white_bijkamer_dimmer
    condition:
      condition: numeric_state
      entity_id: input_number.hue_white_bijkamer_dimmer
      above: 0
    action:
      service: light.turn_on
      data_template:
        entity_id: light.hue_white_bijkamer
        brightness: '{{states.input_number.hue_white_bijkamer_dimmer.state | int}}'
  - alias: 'hue_white_bijkamer reactie'
    trigger:
      platform: state
      entity_id: light.hue_white_bijkamer
      to: 'off'
    action:
      service: input_number.set_value
      data:
        entity_id: input_number.hue_white_bijkamer_dimmer
        value: '0'
  - alias: 'hue_white_bijkamer dimmer reactie aan'
    trigger:
      platform: state
      entity_id: light.hue_white_bijkamer
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.hue_white_bijkamer_dimmer
        value: '{{states.light.hue_white_bijkamer.attributes.brightness}}'

# SENSORS #
  - alias: 'Arlo no motion after 30 seconds'
    trigger:
      platform: state
      entity_id: input_boolean.turn_off
      to: 'on'
      for:
        seconds: 30
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input.boolean.arlo_motion_input

# ALARM #
  - alias: 'Disarm when home'
    trigger:
      platform: state
      entity_id: group.tracking
      to: 'home'
    action:
      service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.alarm
  - alias: 'Arm when away'
    trigger:
      platform: state
      entity_id: group.tracking
      to: 'not_home'
    action:
      service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.alarm
  - alias: 'Alarm Away'
    trigger:
      - platform: state
        entity_id: binary_sensor.sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_halboven
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_bijkamer
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_arlo
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_away
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
  - alias: 'Alarm Home'
    trigger:
      - platform: state
        entity_id: binary_sensor.sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_bijkamer
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: armed_home
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
  - alias: 'Send notification when alarm triggered'
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'triggered'
    action:
      - service: notify.notify
        data:
          message: "ALARM! Beweging gedetecteerd in de Spoorstraat"
      - service: command_line.start_siren
