sensor.alarm_level:
  ignored: true
  polling_intensity: 0
sensor.alarm_type:
  ignored: true
  polling_intensity: 0
sensor.aeotec_zw100_multisensor_6_burglar:
  ignored: true
  polling_intensity: 0
sensor.aeotec_zw100_multisensor_6_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.aeotec_zw100_multisensor_6_ultraviolet:
  ignored: true
  polling_intensity: 0
